### ISSUE TITLE
expand_argument

### ISSUE THREAD

**Issue by thosakwe** [DeviNoles/COP4610_Project1#1]
* Take in a string (char*)
* Should return a dynamically-allocated string, so that we can free() it later
* `strdup` works if nothing is changed
* Look at the first character of the string
* Check if it's $ or ~
* Do appropriate logic
* Probably do some arithmetic to compute the right length of string buffers
* strlen, strcpy

**Comment by DeviNoles** [comment]
Just pushed this into the repository.
https://github.com/DeviNoles/COP4610_Project1/commit/d883bf0bd69b4deff5ee1b53e34fcb0a5f08389e
